### ISSUE TITLE
Loading data class

### ISSUE THREAD

**Issue by chriskamphuis** [Chriskamphuis/ASR#1]
A class for loading data and converting it to MFCC features. Also make a loader for the frequency bank features. And make some useful (help) functions you can think of. 

E.g.:
Functions for:

- Extracting features
- Saving/loading to file

**Comment by chriskamphuis** [comment]
For TIMIT you need the audio (wav) and the PHN files. The PHN files specify the manually verified phone labels and their onset and offset (per file).


if you have an account (these accounts can be available any moment):

for all TIMIT data: /vol/bigdata/smurfland_archive/databases/TIMIT

For 16kHz versions of TIMIT Fwavfiles: /vol/tensusers/ltenbosch/TIMIT/wavfiles16kHz


if you do not have an account yet:

I could prepare an tfp, just for this purpose. Or pass by with a hard disk or usb.  It's about 1.5 GB

**Comment by KDercksen** [comment]
https://github.com/jameslyons/python_speech_features useful perhaps?
